### ISSUE TITLE
System.ArgumentNullException : Value cannot be null. (Parameter 'language') at Simplify.Web.Modules.Data.FileReader.GetFilePath(String fileName, String language)

### ISSUE THREAD

**Issue by i4004** [SimplifyNet/Simplify.Web#174]
System.ArgumentNullException : Value cannot be null. (Parameter 'language') at Simplify.Web.Modules.Data.FileReader.GetFilePath(String fileName, String language)

Change target framework of a project using Simplify.Web to `.NET 6` and launch it in `sdk:6.0-alpine` docker container

**Expected behavior**
No Exceptions

**Desktop (please complete the following information):**
 - OS: sdk:6.0-alpine docker container

**Additional context**
More details:
https://github.com/the-benchmarker/web-frameworks/runs/4144664560?check_suite_focus=true
https://github.com/the-benchmarker/web-frameworks/pull/4815

**Comment by i4004** [comment]
I was able to reproduce this inside local container, will find for a solution.

**Comment by i4004** [comment]
So, I found the problem.

# Cause

Simplify.Web, by default, tries to set  `Thread.CurrentThread.CurrentCulture` to `en` and gets exception: `CultureNotFoundException - Culture is not supported. Parameter name: name en is an invalid culture identifier. `

That's because `aspnet:6.0-alpine` does not have package with cultures installed, so only `iv` (Invariant) culture is available.

If we try to set `<InvariantGlobalization>false</InvariantGlobalization>` parameter in csproj, then in runtime we got: `Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.`

# Solution

Install `libicu` in docker file in app run step

```docker
RUN apk add icu
```
